sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_326343ebfff0_key -iv $encrypted_326343ebfff0_iv
    -in deploy_key.enc -out ./deploy_key -d
  - docker build -t complex/client -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true complex/client npm run test -- --coverage
after_success:
  - docker build -t pramindanata/complex-client ./client
  - docker build -t pramindanata/complex-server ./server
  - docker build -t pramindanata/complex-worker ./worker
  - docker build -t pramindanata/complex-nginx ./nginx
  # Login to Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to Docker Hub
  - docker push pramindanata/complex-client
  - docker push pramindanata/complex-server
  - docker push pramindanata/complex-worker
  - docker push pramindanata/complex-nginx
before_deploy:
  - openssl aes-256-cbc -K $encrypted_326343ebfff0_key -iv $encrypted_326343ebfff0_iv -in deploy_key.enc -out deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - echo -e "Host $SERVER_IP\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy_key
deploy:
  on:
    branch: master
  provider: script
  script: rsync -rav --exclude-from='rsync-exclude.txt' --delete ./ travis@$SERVER_IP:$APP_PATH
after_deploy:
  - ssh -i ./deploy_key travis@$SERVER_IP "cd $APP_PATH && bash install.sh"